name: pyremap-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - pytest
    - numpy
    - scipy
    - netcdf4
    - xarray
    - dask
    - pyproj <= 1.9.6
    - sphinx
    - mock
    - sphinx_rtd_theme
    - numpydoc
