name: CI/CD Release Workflow

on:
  push:
    branches:
      - main

  release:
    types: [published]

env:
  PYTHON_VERSION: "3.13"

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "pyremap_ci"
          miniforge-version: latest
          channels: conda-forge
          channel-priority: strict
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pyremap
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          conda create -n pyremap_dev --file dev-spec.txt \
            python=${{ env.PYTHON_VERSION }}
          conda activate pyremap_dev
          python -m pip install -vv --no-deps --no-build-isolation .

      - name: Build Sphinx Docs
        run: |
          set -e
          conda activate pyremap_dev
          pip check
          cd docs
          sphinx-multiversion . _build/html

      - name: Copy Docs and Commit
        run: |
          set -e
          conda activate pyremap_dev
          pip check
          cd docs
          # gh-pages branch must already exist
          git clone https://github.com/MPAS-Dev/pyremap.git --branch gh-pages --single-branch gh-pages
          # Make sure we're in the gh-pages directory.
          cd gh-pages
          # Create `.nojekyll` (if it doesn't already exist) for proper GH Pages configuration.
          touch .nojekyll
          # Add `index.html` to point to the `main` branch automatically.
          printf '<meta http-equiv="refresh" content="0; url=./main/index.html" />' > index.html
          # Only replace docs in a directory with the destination branch name with latest changes. Docs for
          # releases should be untouched.
          rm -rf ${{ github.head_ref || github.ref_name }}
          # don't clobber existing release versions (in case we retroactively fixed them)
          cp -r -n ../_build/html/* .
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # The second command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: docs/gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
