name: Lint

on:
  pull_request:
    branches: [main]
    paths:
      - '**.py'

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: pyremap
          config: flake8.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
