name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **.py

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - uses: TrueBrain/actions-flake8@v2
      with:
        path: pyremap
        max_line_length: 79
        extra_arguments: "${{steps.changed-files.outputs.all_changed_files}}"
